import { SELECTED_CANDIDATE_STATUS } from '@/constants/common'

export const SORT_STATUS_ORDER = {
  [SELECTED_CANDIDATE_STATUS.notStarted]: 1,
  [SELECTED_CANDIDATE_STATUS.inProgress]: 2,
  [SELECTED_CANDIDATE_STATUS.interview]: 3,
  [SELECTED_CANDIDATE_STATUS.adopted]: 4,
  [SELECTED_CANDIDATE_STATUS.notAdopted]: 5,
  [SELECTED_CANDIDATE_STATUS.cancel]: 6,
}

export const INTERVIEW_STATUS = [
  SELECTED_CANDIDATE_STATUS.interview,
  SELECTED_CANDIDATE_STATUS.adopted,
  SELECTED_CANDIDATE_STATUS.notAdopted,
  SELECTED_CANDIDATE_STATUS.cancel,
]
