import Layout from '@/components/layouts/Layout'
import components from '@/theme/override/components'
import token from '@/theme/override/token'
import { App, ConfigProvider } from 'antd'
import type { Metadata } from 'next'
import './styles/globals.css'
import './styles/date_time_picker.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    custom: 'link',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <ConfigProvider
          theme={{
            components,
            token,
          }}
        >
          <App>
            <Layout>{children}</Layout>
          </App>
        </ConfigProvider>
      </body>
    </html>
  )
}
